# Generated by Django 2.0.2 on 2018-04-19 06:03

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ImageCommments',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='serviceProvidersImages/%Y/%m/%d')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('descriptions', models.TextField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ImageComments')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ServiceNames',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=40)),
                ('personal_descriptions', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+255******'. Up to 9 character is allowed.", regex='^\\+255?\\d{9}$')])),
            ],
            options={
                'verbose_name_plural': 'serviceProviders',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('sh', 'sh'), ('$', '$')], max_length=40)),
                ('discriptions', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ServiceName')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ServiceProviders')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'videoComments',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='serviceProvidersVideos/%Y/%m/%d')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('descriptions', models.TextField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.VideoComments')),
                ('service_proviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ServiceProviders')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='service_proviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ServiceProviders'),
        ),
    ]
