# Generated by Django 2.0.4 on 2018-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviders',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
