# Generated by Django 2.0.2 on 2018-04-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0002_serviceproviders_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='comments',
        ),
        migrations.AddField(
            model_name='imagecomments',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.Images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
