# Generated by Django 2.0.2 on 2018-04-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0003_auto_20180429_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='comments',
        ),
        migrations.AddField(
            model_name='videocomments',
            name='video',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.Videos'),
        ),
    ]
