# Generated by Django 2.0.2 on 2018-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0004_auto_20180429_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
