# Generated by Django 2.0.2 on 2018-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0005_auto_20180429_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='personal_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
