# Generated by Django 2.0.4 on 2018-05-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0008_auto_20180505_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicename',
            options={},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'ServiceNames'},
        ),
        migrations.RemoveField(
            model_name='servicename',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Sname', to='serviceProviders.ServiceName'),
        ),
    ]
