# Generated by Django 2.0.4 on 2018-05-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0009_auto_20180505_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
