# Generated by Django 2.0.4 on 2018-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0012_serviceproviders_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
