# Generated by Django 2.0.4 on 2018-05-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0015_auto_20180515_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='dislikes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
