# Generated by Django 2.0.2 on 2018-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0016_auto_20180515_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=40, null=True),
        ),
    ]
