# Generated by Django 2.0.4 on 2018-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0017_auto_20180621_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created_ate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
