# Generated by Django 2.0.4 on 2018-06-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0018_images_created_ate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='created_ate',
            new_name='created_date',
        ),
    ]
