# Generated by Django 2.0.4 on 2018-06-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0019_auto_20180627_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomments',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='serviceProviders.Images'),
        ),
    ]
