# Generated by Django 2.0.4 on 2018-06-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0021_auto_20180627_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecomments',
            options={},
        ),
    ]
