# Generated by Django 2.0.4 on 2018-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0022_auto_20180627_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(upload_to='serviceProvidersImages/%Y/%m/%d'),
        ),
    ]
