# Generated by Django 2.0.4 on 2018-07-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProviders', '0023_auto_20180719_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviders',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
