# Generated by Django 2.0.4 on 2018-06-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceProviders', '0022_auto_20180627_0911'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('token_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('returned_names', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_to_service', to='serviceProviders.Services')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_to_service_provider', to='serviceProviders.ServiceProviders')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
