# Generated by Django 2.0.4 on 2018-06-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceProviders', '0022_auto_20180627_0911'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProviders.ServiceProviders')),
            ],
        ),
    ]
