# Generated by Django 2.0.4 on 2018-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180628_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='event_date',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
